document.querySelector('.brand-icon')?.setAttribute('src','./brand-mark.svg');
import('./pdf-export.js?v=822').catch(err=>console.error('PDF export konnte nicht geladen werden',err));

// v8.32 – zentrale Ergebnisansicht
(function(){
  const more=document.getElementById('tab-mehr'),main=document.querySelector('main'),nav=document.querySelector('nav');
  if(!more||!main||!nav||document.getElementById('tab-ergebnis'))return;
  const st=document.createElement('style');st.textContent=`.result-entry{border:1px solid #cfe0ff;background:#f7faff}.result-entry p{font-size:12px;line-height:1.5;color:#56627a;margin:0 0 12px}.result-top{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.result-back{border:1px solid #d8deea;background:#f3f6fb;color:var(--navy);border-radius:10px;padding:8px 11px;font-size:12px;font-weight:800;white-space:nowrap}.overview-hero{border:2px solid #9bd7ae;background:#f2fbf5;border-radius:20px;padding:20px 16px;margin:16px 0;text-align:center}.overview-hero .eyebrow{font-size:11px;font-weight:800;color:#39724b;text-transform:uppercase}.overview-hero .big{font-size:35px;font-weight:850;color:var(--green);margin:7px 0 5px;font-variant-numeric:tabular-nums}.overview-hero .sub{font-size:12px;color:var(--muted)}.overview-kpis{display:grid;grid-template-columns:1fr 1fr;gap:9px}.overview-kpi{border:1px solid var(--line);border-radius:14px;background:#fff;padding:12px 9px;text-align:center}.overview-kpi span{display:block;font-size:10px;color:var(--muted)}.overview-kpi strong{display:block;font-size:17px;color:var(--navy);margin-top:5px}.overview-empty{border:1px dashed #cfd6e2;border-radius:14px;padding:13px;background:#fafbfd;font-size:12px;line-height:1.45;color:#657086}.overview-jump{margin-top:9px;width:100%;border:1px solid #d8deea;background:#f3f6fb;color:var(--navy);border-radius:10px;padding:9px;font-size:12px;font-weight:800}.overview-eval{border:1px solid #d9c9fa;background:#fcfaff;border-radius:16px;padding:15px 16px;line-height:1.55;font-size:13px;color:#4f3b65}.overview-eval b{color:#7e22ce}`;document.head.appendChild(st);
  const entry=document.createElement('div');entry.className='card result-entry';entry.innerHTML='<h3>📊 Dein Job auf einen Blick</h3><p>Stundenwert, Teilzeit, Jobvergleich und Wunschgehalt in einer zentralen Ergebnisansicht.</p><button class="primary" id="openResultDashboard">Ergebnis ansehen →</button>';more.querySelector('.section-title')?.after(entry);
  const s=document.createElement('section');s.id='tab-ergebnis';s.className='hidden';s.innerHTML=`<div class="result-top"><div><h2 class="section-title">Dein Job auf einen Blick</h2><div class="section-sub">Geld, Zeit und Entscheidungen in einer Übersicht.</div></div><button class="result-back" id="resultBack">← Zurück</button></div><div class="info"><b>Live-Auswertung:</b> Die Übersicht nutzt deine aktuellen Eingaben und bereits berechneten Szenarien.</div><div class="overview-hero"><div class="eyebrow">Dein aktueller Netto-Stundenwert</div><div class="big" id="ovNH"></div><div class="sub" id="ovSub"></div></div><div class="overview-kpis"><div class="overview-kpi"><span>Monatsnetto</span><strong id="ovNet"></strong></div><div class="overview-kpi"><span>Netto / Jahr</span><strong id="ovYear"></strong></div><div class="overview-kpi"><span>Wochenstunden</span><strong id="ovWH"></strong></div><div class="overview-kpi"><span>Ø Stunden / Monat</span><strong id="ovMH"></strong></div></div><div class="card"><h3>💼 Dein aktuelles Modell</h3><div class="rows"><div class="row"><span>Brutto / Monat</span><strong id="ovGross"></strong></div><div class="row"><span>Netto / Monat</span><strong id="ovNet2"></strong></div><div class="row"><span>Brutto / Stunde</span><strong id="ovGH"></strong></div><div class="row"><span>Netto / Stunde</span><strong id="ovNH2"></strong></div><div class="row"><span>Vertragsarbeitszeit / Jahr</span><strong id="ovAH"></strong></div></div></div><div class="card"><h3>⏳ Teilzeit</h3><div id="ovPT"></div></div><div class="card"><h3>⚖ Jobvergleich</h3><div id="ovCmp"></div></div><div class="card"><h3>🎯 Wunschgehalt</h3><div id="ovTarget"></div></div><div class="overview-eval" id="ovEval"></div><button class="primary" id="ovRefresh" style="margin-top:14px">Ergebnis aktualisieren</button>`;main.insertBefore(s,more);
  const ready=id=>{const e=document.getElementById(id);return e&&!e.classList.contains('hidden')},jump=(tab,text)=>`<button class="overview-jump" data-ov="${tab}">${text}</button>`;
  function bind(){s.querySelectorAll('[data-ov]').forEach(b=>b.onclick=()=>{s.classList.add('hidden');nav.querySelector(`button[data-tab="${b.dataset.ov}"]`)?.click()})}
  function update(){
    const g=Math.max(0,typeof monthGross==='function'?monthGross():0),h=Math.max(0,+($('hours')?.value||0)),mh=h*52/12,n=calcNet(g),nh=mh?n/mh:0;
    $('ovNH').textContent=eur(nh);$('ovSub').textContent=`${eur(n,0)} netto pro Monat · ${nf(h,1)} Std. pro Woche`;$('ovNet').textContent=eur(n,0);$('ovYear').textContent=eur(n*12,0);$('ovWH').textContent=nf(h,1)+' Std.';$('ovMH').textContent=nf(mh,1)+' Std.';$('ovGross').textContent=eur(g,0);$('ovNet2').textContent=eur(n,0);$('ovGH').textContent=eur(mh?g/mh:0);$('ovNH2').textContent=eur(nh);$('ovAH').textContent=nf(h*52,0)+' Std.';
    const bits=[`Dein aktueller Netto-Stundenwert liegt bei <b>${eur(nh)}</b>.`];
    if(ready('parttimeResult')){const pg=+$('ptGross').value,hn=+$('ptHoursNow').value,hz=+$('ptHoursNew').value;if(pg&&hn&&hz<hn){const gn=pg*hz/hn,nn=calcNet(gn),loss=calcNet(pg)-nn,free=(hn-hz)*52,cost=loss/((hn-hz)*52/12);$('ovPT').innerHTML=`<div class="rows"><div class="row"><span>Modell</span><strong>${nf(hn,1)} → ${nf(hz,1)} Std.</strong></div><div class="row"><span>Teilzeit-Netto / Monat</span><strong>${eur(nn,0)}</strong></div><div class="row"><span>Netto weniger / Monat</span><strong>− ${eur(loss,0)}</strong></div><div class="row"><span>Mehr freie Zeit / Jahr</span><strong>+ ${nf(free,0)} Std.</strong></div><div class="row"><span>Preis je freier Stunde</span><strong>${eur(cost)}</strong></div></div>`;bits.push(`Dein Teilzeitmodell bringt rund <b>${nf(free,0)} Stunden mehr Freizeit pro Jahr</b>; jede zusätzliche freie Stunde kostet etwa <b>${eur(cost)}</b> netto.`)}}else $('ovPT').innerHTML=`<div class="overview-empty">Noch kein Teilzeitvergleich berechnet.</div>${jump('teilzeit','Zum Teilzeitvergleich →')}`;
    if(ready('compareResult')&&typeof job==='function'){try{const a=job('A'),b=job('B'),na=$('nameA').value||'Job A',nb=$('nameB').value||'Job B',w=b.effectiveNetHour>a.effectiveNetHour?nb:na,d=Math.abs(b.effectiveNetHour-a.effectiveNetHour);$('ovCmp').innerHTML=`<div class="rows"><div class="row"><span>${na} effektiv</span><strong>${eur(a.effectiveNetHour)}/Std.</strong></div><div class="row"><span>${nb} effektiv</span><strong>${eur(b.effectiveNetHour)}/Std.</strong></div><div class="row"><span>Höherer effektiver Jobwert</span><strong>${w}</strong></div><div class="row"><span>Vorsprung</span><strong>${eur(d)}/Std.</strong></div></div>`;bits.push(`Im Jobvergleich liegt <b>${w}</b> beim effektiven Jobwert um <b>${eur(d)} je gebundener Stunde</b> vorn.`)}catch{$('ovCmp').innerHTML=`<div class="overview-empty">Jobvergleich bitte erneut berechnen.</div>${jump('vergleich','Jobvergleich öffnen →')}`}}else $('ovCmp').innerHTML=`<div class="overview-empty">Noch kein Jobvergleich berechnet.</div>${jump('vergleich','Zum Jobvergleich →')}`;
    if(ready('targetResult')){const th=+$('targetHours').value,t=+$('targetHour').value,target=t*th*52/12,tg=findGross(target);$('ovTarget').innerHTML=`<div class="rows"><div class="row"><span>Ziel Netto / Stunde</span><strong>${eur(t)}</strong></div><div class="row"><span>Benötigtes Monatsbrutto</span><strong>${eur(tg,0)}</strong></div><div class="row"><span>Benötigtes Jahresbrutto</span><strong>${eur(tg*12,0)}</strong></div></div>`;bits.push(`Für dein Ziel von <b>${eur(t)} netto je Stunde</b> brauchst du etwa <b>${eur(tg,0)} brutto im Monat</b>.`)}else $('ovTarget').innerHTML=`<div class="overview-empty">Noch kein Wunschgehalt berechnet.</div>${jump('wunsch','Zum Wunschgehalt →')}`;
    $('ovEval').innerHTML='<b>WasBinIchWert-Bewertung</b><br>'+bits.join(' ');bind();
  }
  function open(){document.querySelectorAll('main > section[id^="tab-"]').forEach(x=>x.classList.add('hidden'));s.classList.remove('hidden');update();scrollTo(0,0)}
  function back(){s.classList.add('hidden');more.classList.remove('hidden');nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.tab==='mehr'));scrollTo(0,0)}
  $('openResultDashboard').onclick=open;$('resultBack').onclick=back;$('ovRefresh').onclick=update;nav.addEventListener('click',()=>s.classList.add('hidden'),true);
})();