// WasBinIchWert v8.31 – Teilzeitvergleich mit Modellvergleich
(function initPartTimeComparison(){
  if(document.getElementById('tab-teilzeit')) return;

  const main=document.querySelector('main');
  const more=document.getElementById('tab-mehr');
  const nav=document.querySelector('nav');
  if(!main||!more||!nav) return;

  const style=document.createElement('style');
  style.textContent=`
    .parttime-hero{border:2px solid #9bd7ae;background:#f2fbf5;border-radius:20px;padding:18px 14px;margin:16px 0;text-align:center}
    .parttime-hero.effective{border-color:#d9c9fa;background:#fcfaff}
    .parttime-hero .eyebrow{font-size:11px;font-weight:800;color:#39724b;text-transform:uppercase;letter-spacing:.04em}
    .parttime-hero.effective .eyebrow{color:#7e22ce}.parttime-hero .big{font-size:31px;line-height:1.08;font-weight:850;color:var(--green);margin:7px 0 4px;font-variant-numeric:tabular-nums}.parttime-hero.effective .big{color:#7e22ce}.parttime-hero .sub{font-size:12px;color:var(--muted);line-height:1.45}
    .parttime-kpis{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:12px 0}.parttime-kpi{border:1px solid var(--line);border-radius:14px;background:#fff;padding:12px 9px;text-align:center}.parttime-kpi span{display:block;font-size:10px;color:var(--muted);line-height:1.3}.parttime-kpi strong{display:block;font-size:18px;color:var(--navy);margin-top:5px;font-variant-numeric:tabular-nums}.parttime-copy{font-size:12px;line-height:1.5;color:#40506a}
    #parttimeSync{width:100%;border:1px solid #d8deea;background:#f3f6fb;color:var(--navy);border-radius:11px;padding:10px 12px;font-size:12px;font-weight:800;margin-top:12px}.pt-pro{margin-top:16px;padding-top:15px;border-top:1px solid var(--line)}.pt-pro>summary{cursor:pointer;font-weight:800;color:var(--blue);list-style:none;line-height:1.4}.pt-pro-note{font-size:11px;color:#69748b;line-height:1.45;margin:9px 0 4px}
    .pt-models{display:grid;gap:8px;margin-top:12px}.pt-model{display:grid;grid-template-columns:50px minmax(0,1fr) minmax(0,1fr);gap:8px;align-items:center;border:1px solid var(--line);border-radius:13px;padding:10px;background:#fff}.pt-model.current{background:#f4f7fb}.pt-model.selected{border:2px solid #9bd7ae;background:#f2fbf5}.pt-model b{font-size:13px;color:var(--navy)}.pt-model span{font-size:10px;color:var(--muted);display:block}.pt-model strong{display:block;font-size:13px;color:var(--navy);margin-top:2px;font-variant-numeric:tabular-nums}.pt-model .cost{color:var(--green)}.pt-model-head{display:grid;grid-template-columns:50px minmax(0,1fr) minmax(0,1fr);gap:8px;font-size:9px;font-weight:800;color:#6b7589;padding:0 10px;text-transform:uppercase}.pt-model-note{font-size:10px;color:#69748b;line-height:1.4;margin-top:9px}
    nav{grid-template-columns:repeat(5,1fr)}@media(max-width:400px){nav{font-size:9.5px}.parttime-kpi strong{font-size:16px}.parttime-hero .big{font-size:28px}.pt-model{grid-template-columns:45px minmax(0,1fr) minmax(0,1fr);padding:9px 7px}.pt-model-head{grid-template-columns:45px minmax(0,1fr) minmax(0,1fr);padding:0 7px}}
  `;
  document.head.appendChild(style);

  const section=document.createElement('section');section.id='tab-teilzeit';section.className='hidden';section.innerHTML=`
    <h2 class="section-title">Teilzeit vergleichen</h2><div class="section-sub">Was kostet dich weniger Arbeitszeit – und wie viel freie Zeit gewinnst du?</div>
    <div class="info"><b>So wird gerechnet:</b> Dein Teilzeit-Brutto wird zunächst proportional zu den Wochenstunden berechnet. Optional kannst du im PRO-Bereich zusätzlich Arbeitsweg, Homeoffice und reale Jobkosten einbeziehen. Deine Angaben aus „Meine Daten“ gelten automatisch für die Netto-Berechnung.</div>
    <div class="card"><h3>Ausgangsmodell</h3><label>Bruttogehalt pro Monat</label><div class="field big"><input id="ptGross" type="number" value="4200" min="0" step="50"><span class="suffix">€</span></div><div class="grid2"><div><label>Wochenstunden aktuell</label><div class="field"><input id="ptHoursNow" type="number" value="40" min="1" step="0.5"><span class="suffix">Std.</span></div></div><div><label>Arbeitstage aktuell</label><div class="field"><input id="ptDaysNow" type="number" value="5" min="1" max="7" step="1"><span class="suffix">Tage</span></div></div></div><button id="parttimeSync" type="button">Werte aus Rechner übernehmen</button></div>
    <div class="card"><h3>Gewünschtes Teilzeitmodell</h3><div class="grid2"><div><label>Wochenstunden neu</label><div class="field"><input id="ptHoursNew" type="number" value="32" min="1" step="0.5"><span class="suffix">Std.</span></div></div><div><label>Arbeitstage neu</label><div class="field"><input id="ptDaysNew" type="number" value="4" min="1" max="7" step="1"><span class="suffix">Tage</span></div></div></div><div class="info" id="ptPreview"></div>
      <details class="pt-pro"><summary>Effektiven Teilzeitwert berücksichtigen <span class="pro-badge">PRO</span></summary><div class="pt-pro-note">Berücksichtigt zusätzlich die tatsächlich gewonnene Zeit sowie Veränderungen bei Pendeln, Homeoffice und arbeitsbedingten Kosten.</div><div class="grid2">
        <div><label>Urlaubstage aktuell/Jahr</label><div class="field"><input id="ptVacation" type="number" value="30" min="0" step="1"><span class="suffix">Tage</span></div></div><div><label>Kosten je km</label><div class="field"><input id="ptKmCost" type="number" value="0.30" min="0" step="0.01"><span class="suffix">€</span></div></div><div><label>Homeoffice aktuell</label><div class="field"><input id="ptHomeNow" type="number" value="0" min="0" step="0.5"><span class="suffix">Tage</span></div></div><div><label>Homeoffice neu</label><div class="field"><input id="ptHomeNew" type="number" value="0" min="0" step="0.5"><span class="suffix">Tage</span></div></div><div><label>Arbeitsweg einfach</label><div class="field"><input id="ptKm" type="number" value="0" min="0" step="1"><span class="suffix">km</span></div></div><div><label>Fahrtzeit einfach</label><div class="field"><input id="ptMinutes" type="number" value="0" min="0" step="1"><span class="suffix">Min.</span></div></div><div><label>Parkkosten pro Bürotag</label><div class="field"><input id="ptParking" type="number" value="0" min="0" step="0.5"><span class="suffix">€</span></div></div><div><label>Verpflegung extra/Bürotag</label><div class="field"><input id="ptFood" type="number" value="0" min="0" step="0.5"><span class="suffix">€</span></div></div><div><label>Kinderbetreuung pro Bürotag</label><div class="field"><input id="ptChildcare" type="number" value="0" min="0" step="0.5"><span class="suffix">€</span></div></div><div><label>Homeoffice-Ersparnis/Tag</label><div class="field"><input id="ptHomeSaving" type="number" value="0" min="0" step="0.5"><span class="suffix">€</span></div></div>
      </div></details></div>
    <button class="primary" id="calcParttime">Teilzeit vergleichen →</button>
    <div id="parttimeResult" class="hidden">
      <div class="parttime-hero"><div class="eyebrow">Preis deiner zusätzlichen Freizeit</div><div class="big" id="ptCostFreeHour"></div><div class="sub" id="ptHeroSub"></div></div>
      <div class="parttime-kpis"><div class="parttime-kpi"><span>Netto weniger / Monat</span><strong id="ptNetLossMonth"></strong></div><div class="parttime-kpi"><span>Freie Zeit mehr / Monat</span><strong id="ptFreeMonth"></strong></div><div class="parttime-kpi"><span>Netto weniger / Jahr</span><strong id="ptNetLossYear"></strong></div><div class="parttime-kpi"><span>Freie Zeit mehr / Jahr</span><strong id="ptFreeYear"></strong></div></div>
      <div class="card"><div class="rows"><div class="row"><span>Aktuelles Monatsbrutto</span><strong id="ptGrossNowOut"></strong></div><div class="row"><span>Teilzeit-Monatsbrutto</span><strong id="ptGrossNewOut"></strong></div><div class="row"><span>Aktuelles Monatsnetto</span><strong id="ptNetNowOut"></strong></div><div class="row"><span>Teilzeit-Monatsnetto</span><strong id="ptNetNewOut"></strong></div><div class="row"><span>Netto-Stundenwert aktuell</span><strong id="ptHourNowOut"></strong></div><div class="row"><span>Netto-Stundenwert Teilzeit</span><strong id="ptHourNewOut"></strong></div><div class="row"><span>Zusätzliche freie Tage/Jahr</span><strong id="ptFreeDaysOut"></strong></div></div></div>
      <div class="card"><h3>Weitere Teilzeitmodelle auf einen Blick</h3><div class="pt-model-head"><div>Std.</div><div>Netto / Monat</div><div>Freizeit kostet</div></div><div class="pt-models" id="ptModels"></div><div class="pt-model-note">Verglichen wird mit deinem aktuellen Modell. Das Brutto wird proportional zur Arbeitszeit reduziert; die Netto-Berechnung nutzt „Meine Daten“. Grün markiert ist dein gewähltes Modell.</div></div>
      <div class="parttime-hero effective"><div class="eyebrow">Effektiver Preis deiner Freizeit <span class="pro-badge">PRO</span></div><div class="big" id="ptEffectiveCostHour"></div><div class="sub">inkl. Urlaub, gesparter Pendelzeit und veränderter Jobkosten</div></div>
      <div class="card"><h3>Effektiver Teilzeitwert <span class="pro-badge">PRO</span></h3><div class="rows"><div class="row"><span>Tatsächlich gewonnene Zeit/Jahr</span><strong id="ptActualFreeYear"></strong></div><div class="row"><span>Davon gesparte Pendelzeit</span><strong id="ptCommuteTimeSaved"></strong></div><div class="row"><span>Weniger Fahrtkosten/Jahr</span><strong id="ptCommuteCostSaved"></strong></div><div class="row"><span>Weitere Jobkosten-Ersparnis/Jahr</span><strong id="ptOtherCostSaved"></strong></div><div class="row"><span>Homeoffice-Effekt/Jahr</span><strong id="ptHomeSavingDiff"></strong></div><div class="row"><span>Effektive Nettoeinbuße/Monat</span><strong id="ptEffectiveLossMonth"></strong></div></div></div><div class="summary parttime-copy" id="ptEffectiveSummary"></div><div class="summary parttime-copy" id="ptSummary"></div>
    </div>`;
  main.insertBefore(section,more);
  const btn=document.createElement('button');btn.dataset.tab='teilzeit';btn.innerHTML='<b>◷</b>Teilzeit';nav.insertBefore(btn,nav.lastElementChild);
  const settingsHint=document.querySelector('.settings-head > div > div[style*="font-size:11px"]');if(settingsHint)settingsHint.textContent='Gilt automatisch für Rechner, Vergleich, Wunschgehalt und Teilzeit.';
  const tabs=['rechner','vergleich','wunsch','teilzeit','mehr'];document.querySelectorAll('nav button').forEach(navBtn=>{navBtn.onclick=()=>{document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));navBtn.classList.add('active');tabs.forEach(t=>document.getElementById('tab-'+t)?.classList.toggle('hidden',t!==navBtn.dataset.tab));scrollTo(0,0);};});

  const val=id=>Math.max(0,+document.getElementById(id).value||0);const signedMoney=(n,d=0)=>(n>=0?'+ ':'− ')+eur(Math.abs(n),d);
  const updatePreview=()=>{const g=val('ptGross'),hNow=val('ptHoursNow'),hNew=val('ptHoursNew');const projected=hNow?g*hNew/hNow:0;document.getElementById('ptPreview').textContent=hNow?`Bei proportionaler Kürzung entspricht das etwa ${eur(projected,0)} brutto pro Monat.`:'Bitte aktuelle Wochenstunden eingeben.';};
  ['ptGross','ptHoursNow','ptHoursNew'].forEach(id=>document.getElementById(id)?.addEventListener('input',updatePreview));
  document.getElementById('parttimeSync').onclick=()=>{const sourceGross=typeof monthGross==='function'?monthGross():+(document.getElementById('salary')?.value||0);const sourceHours=+(document.getElementById('hours')?.value||0);if(sourceGross>0)document.getElementById('ptGross').value=Math.round(sourceGross*100)/100;if(sourceHours>0)document.getElementById('ptHoursNow').value=sourceHours;updatePreview();};

  const renderModels=(gNow,hNow,nNow,hSelected)=>{
    const presets=[40,35,32,30,25,20].filter(h=>h<=hNow);
    if(!presets.some(h=>Math.abs(h-hNow)<.01))presets.unshift(hNow);
    if(!presets.some(h=>Math.abs(h-hSelected)<.01))presets.push(hSelected);
    const hours=[...new Set(presets.map(h=>+h.toFixed(2)))].sort((a,b)=>b-a);
    const box=document.getElementById('ptModels');box.innerHTML='';
    hours.forEach(h=>{const gross=gNow*h/hNow,net=calcNet(gross),loss=nNow-net,freeMonth=(hNow-h)*52/12,cost=freeMonth>0?loss/freeMonth:0;const row=document.createElement('div');row.className='pt-model'+(Math.abs(h-hNow)<.01?' current':'')+(Math.abs(h-hSelected)<.01?' selected':'');row.innerHTML=`<b>${nf(h,1)}</b><div><span>${Math.abs(h-hNow)<.01?'aktuell':eur(gross,0)+' brutto'}</span><strong>${eur(net,0)}</strong></div><div><span>${h<hNow?'− '+eur(Math.max(0,loss),0)+' / Mon.':'Ausgangswert'}</span><strong class="cost">${h<hNow?eur(cost)+'/Std.':'–'}</strong></div>`;box.appendChild(row);});
  };

  document.getElementById('calcParttime').onclick=()=>{
    const gNow=val('ptGross'),hNow=val('ptHoursNow'),hNew=val('ptHoursNew'),dNow=Math.max(1,val('ptDaysNow')||5),dNew=Math.max(1,val('ptDaysNew')||dNow),result=document.getElementById('parttimeResult'),summary=document.getElementById('ptSummary');
    if(!gNow||!hNow||!hNew){result.classList.remove('hidden');summary.textContent='⚠️ Bitte Bruttogehalt sowie aktuelle und gewünschte Wochenstunden vollständig eingeben.';return;}if(hNew>=hNow){result.classList.remove('hidden');summary.textContent='⚠️ Für den Teilzeitvergleich müssen die gewünschten Wochenstunden unter den aktuellen Wochenstunden liegen.';return;}if(dNew>dNow){result.classList.remove('hidden');summary.textContent='⚠️ Die Zahl der neuen Arbeitstage sollte für diesen Teilzeitvergleich nicht über den aktuellen Arbeitstagen liegen.';return;}
    const gNew=gNow*hNew/hNow,nNow=calcNet(gNow),nNew=calcNet(gNew),netLossMonth=nNow-nNew,netLossYear=netLossMonth*12,freeWeek=hNow-hNew,freeMonth=freeWeek*52/12,freeYear=freeWeek*52,costPerFreeHour=freeMonth?netLossMonth/freeMonth:0,mhNow=hNow*52/12,mhNew=hNew*52/12,hourNow=nNow/mhNow,hourNew=nNew/mhNew,freeDaysYear=Math.max(0,dNow-dNew)*52;
    document.getElementById('ptCostFreeHour').textContent=eur(costPerFreeHour);document.getElementById('ptHeroSub').textContent=`je zusätzlich gewonnener freier Stunde bei ${nf(freeWeek,1)} Std. weniger pro Woche`;document.getElementById('ptNetLossMonth').textContent='− '+eur(Math.max(0,netLossMonth),0);document.getElementById('ptFreeMonth').textContent='+ '+nf(freeMonth,1)+' Std.';document.getElementById('ptNetLossYear').textContent='− '+eur(Math.max(0,netLossYear),0);document.getElementById('ptFreeYear').textContent='+ '+nf(freeYear,0)+' Std.';document.getElementById('ptGrossNowOut').textContent=eur(gNow,0);document.getElementById('ptGrossNewOut').textContent=eur(gNew,0);document.getElementById('ptNetNowOut').textContent=eur(nNow,0);document.getElementById('ptNetNewOut').textContent=eur(nNew,0);document.getElementById('ptHourNowOut').textContent=eur(hourNow);document.getElementById('ptHourNewOut').textContent=eur(hourNew);document.getElementById('ptFreeDaysOut').textContent=freeDaysYear?'+ '+nf(freeDaysYear,0)+' Tage':'–';renderModels(gNow,hNow,nNow,hNew);

    const vacationDays=val('ptVacation'),vacationWeeks=Math.min(52,vacationDays/dNow),workingWeeks=Math.max(0,52-vacationWeeks),homeNow=Math.min(dNow,val('ptHomeNow')),homeNew=Math.min(dNew,val('ptHomeNew')),officeNow=Math.max(0,dNow-homeNow),officeNew=Math.max(0,dNew-homeNew),commuteDaysNow=officeNow*workingWeeks,commuteDaysNew=officeNew*workingWeeks,km=val('ptKm'),minutes=val('ptMinutes'),kmCost=val('ptKmCost'),parking=val('ptParking'),food=val('ptFood'),childcare=val('ptChildcare'),homeSaving=val('ptHomeSaving');
    const commuteHoursNow=minutes*2*commuteDaysNow/60,commuteHoursNew=minutes*2*commuteDaysNew/60,commuteTimeSaved=commuteHoursNow-commuteHoursNew,commuteCostNow=km*2*commuteDaysNow*kmCost,commuteCostNew=km*2*commuteDaysNew*kmCost,commuteCostSaved=commuteCostNow-commuteCostNew,otherCostNow=(parking+food+childcare)*commuteDaysNow,otherCostNew=(parking+food+childcare)*commuteDaysNew,otherCostSaved=otherCostNow-otherCostNew,homeSaveNow=homeNow*workingWeeks*homeSaving,homeSaveNew=homeNew*workingWeeks*homeSaving,homeSavingDiff=homeSaveNew-homeSaveNow,actualWorkTimeSaved=freeWeek*workingWeeks,actualFreeYear=Math.max(0,actualWorkTimeSaved+commuteTimeSaved),effectiveAnnualNow=nNow*12-commuteCostNow-otherCostNow+homeSaveNow,effectiveAnnualNew=nNew*12-commuteCostNew-otherCostNew+homeSaveNew,effectiveLossYear=effectiveAnnualNow-effectiveAnnualNew,effectiveLossMonth=effectiveLossYear/12,effectiveCostHour=actualFreeYear?effectiveLossYear/actualFreeYear:0;
    document.getElementById('ptActualFreeYear').textContent='+ '+nf(actualFreeYear,0)+' Std.';document.getElementById('ptCommuteTimeSaved').textContent=(commuteTimeSaved>=0?'+ ':'− ')+nf(Math.abs(commuteTimeSaved),1)+' Std.';document.getElementById('ptCommuteCostSaved').textContent=signedMoney(commuteCostSaved,0);document.getElementById('ptOtherCostSaved').textContent=signedMoney(otherCostSaved,0);document.getElementById('ptHomeSavingDiff').textContent=signedMoney(homeSavingDiff,0);document.getElementById('ptEffectiveLossMonth').textContent=effectiveLossMonth>=0?'− '+eur(effectiveLossMonth,0):'+ '+eur(Math.abs(effectiveLossMonth),0);document.getElementById('ptEffectiveCostHour').textContent=effectiveCostHour>=0?eur(effectiveCostHour):'− '+eur(Math.abs(effectiveCostHour));
    const effectBits=[];if(commuteTimeSaved>.05)effectBits.push(`${nf(commuteTimeSaved,0)} Std. weniger Pendelzeit`);if(commuteCostSaved>.5)effectBits.push(`${eur(commuteCostSaved,0)} weniger Fahrtkosten`);if(otherCostSaved>.5)effectBits.push(`${eur(otherCostSaved,0)} weniger weitere Jobkosten`);if(Math.abs(homeSavingDiff)>.5)effectBits.push(`${signedMoney(homeSavingDiff,0)} Homeoffice-Effekt`);const effectiveSummary=document.getElementById('ptEffectiveSummary');effectiveSummary.textContent=effectiveLossYear>=0?`💎 Effektiv sinkt dein verfügbares Netto nach den berücksichtigten Jobkosten um rund ${eur(effectiveLossMonth,0)} pro Monat. Dafür gewinnst du während der tatsächlichen Arbeitswochen inklusive eingesparter Pendelzeit etwa ${nf(actualFreeYear,0)} Stunden pro Jahr. Eine effektiv gewonnene freie Stunde kostet dich damit rund ${eur(effectiveCostHour)}.${effectBits.length?' Größte Effekte: '+effectBits.join(' · ')+'.':''}`:`💎 In dieser Konstellation gleichen die eingesparten Jobkosten den Nettoverlust rechnerisch vollständig aus. Du hast rund ${eur(Math.abs(effectiveLossMonth),0)} pro Monat mehr zur Verfügung und gewinnst gleichzeitig etwa ${nf(actualFreeYear,0)} Stunden Zeit pro Jahr.${effectBits.length?' Effekte: '+effectBits.join(' · ')+'.':''}`;
    const dayText=freeDaysYear?` Wenn du zugleich von ${nf(dNow,0)} auf ${nf(dNew,0)} Arbeitstage pro Woche wechselst, entstehen rechnerisch ${nf(freeDaysYear,0)} zusätzliche arbeitsfreie Tage pro Jahr.`:'';summary.textContent=`💡 ${nf(hNow,1)} → ${nf(hNew,1)} Wochenstunden kosten dich nach der aktuellen 2026er Netto-Berechnung rund ${eur(netLossMonth,0)} netto pro Monat. ${nf(freeWeek,1)} Stunden weniger pro Woche entsprechen rund ${nf(freeMonth,1)} Stunden zusätzlicher Freizeit pro Monat bzw. ${nf(freeYear,0)} Stunden pro Jahr. Eine zusätzliche freie Stunde kostet damit ungefähr ${eur(costPerFreeHour)}.${dayText}`;result.classList.remove('hidden');
  };
  updatePreview();
})();