// WasBinIchWert v8.41 – zentrale Free/PRO-Freischaltlogik
(function(){
  if(window.WIWPro)return;
  const KEY='wasbinichwert-pro-test-access-v1';
  let active=true;try{const s=localStorage.getItem(KEY);active=s===null?true:s==='1';if(s===null)localStorage.setItem(KEY,'1')}catch{}

  const style=document.createElement('style');style.textContent=`
  .pro-access-card{border:1px solid #d9c9fa;background:#fcfaff}.pro-access-head{display:flex;justify-content:space-between;gap:12px}.pro-access-kicker{font-size:10px;font-weight:850;color:#7e22ce;text-transform:uppercase}.pro-access-card p{font-size:12px;line-height:1.5;color:#665776;margin:0}.pro-access-toggle{flex:0 0 auto;border:1px solid #d9c9fa;background:#fff;color:#7e22ce;border-radius:999px;padding:9px 12px;font-size:11px;font-weight:850}.pro-access-toggle.on{background:#7e22ce;color:#fff}.pro-access-state{margin-top:11px;padding:9px 11px;border-radius:11px;background:#fff;border:1px solid #eadffb;font-size:11px;color:#665776}.pro-disabled{opacity:.48}.pro-locked>summary:after{content:'  🔒';font-size:11px}.pro-lockable{position:relative}.pro-lockable.pro-off>*:not(.pro-lock){opacity:.12;pointer-events:none}.pro-lock{display:none;position:absolute;z-index:4;inset:0;align-items:center;justify-content:center;padding:16px;text-align:center}.pro-off>.pro-lock{display:flex}.pro-lock>div{background:#fff;border:1px solid #d9c9fa;border-radius:14px;padding:12px 14px;color:#5f4a73;font-size:12px;box-shadow:0 8px 24px rgba(56,35,84,.10)}.pro-lock b{display:block;color:#7e22ce;margin-bottom:4px}.pro-back{position:fixed;z-index:9999;inset:0;background:rgba(13,27,42,.48);display:flex;align-items:flex-end;justify-content:center;padding:18px}.pro-modal{width:min(440px,100%);background:#fff;border-radius:22px;padding:20px}.pro-modal h3{margin:4px 0 8px}.pro-modal p{font-size:13px;line-height:1.5;color:#5f687a}.pro-modal-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px}.pro-modal button{border-radius:11px;padding:11px;font-size:12px;font-weight:850}.pro-close{border:1px solid #d8deea;background:#f3f6fb}.pro-enable{border:0;background:#7e22ce;color:#fff}`;document.head.appendChild(style);

  function popup(feature){if($('proAccessModal'))return;const b=document.createElement('div');b.id='proAccessModal';b.className='pro-back';b.innerHTML=`<div class="pro-modal"><div class="pro-access-kicker">WasBinIchWert PRO</div><h3>${feature}</h3><p>Diese Funktion gehört zur PRO-Version. Während der Entwicklung kannst du den PRO-Testzugang jederzeit aktivieren.</p><div class="pro-modal-actions"><button class="pro-close">Schließen</button><button class="pro-enable">PRO testen</button></div></div>`;document.body.appendChild(b);b.querySelector('.pro-close').onclick=()=>b.remove();b.querySelector('.pro-enable').onclick=()=>{set(true);b.remove()};b.onclick=e=>{if(e.target===b)b.remove()}}
  function lock(el,title){if(!el)return;el.classList.add('pro-lockable');if(!el.querySelector(':scope>.pro-lock')){const x=document.createElement('div');x.className='pro-lock';x.innerHTML=`<div><b>🔒 ${title}</b>Mit WasBinIchWert PRO verfügbar.</div>`;el.appendChild(x)}}
  function mark(){
    document.querySelectorAll('details.advanced,.pt-pro').forEach(x=>x.dataset.proAction='Effektiver Jobwert');
    [['openSalaryGrowth','Gehaltsentwicklung'],['openNegotiation','Gehaltsverhandlung'],['resultPdfBtn','PDF-Bericht'],['resultShareBtn','Ergebnis teilen'],['saveNamedCompare','Vergleiche speichern']].forEach(([id,n])=>{const e=$(id);if(e)e.dataset.proAction=n});
    lock($('effBoxA')?.closest('.card'),'Effektiver Jobwert');lock($('effectiveComparisonTable'),'Effektiver Jobvergleich');lock($('decisionCard'),'WasBinIchWert-Bewertung');lock(document.querySelector('.saved-panel'),'Mehrere Vergleiche speichern');lock($('resultExportCard'),'Speichern & Teilen');lock($('ptEffectiveCostHour')?.closest('.parttime-hero'),'Effektiver Teilzeitwert');lock($('ptActualFreeYear')?.closest('.card'),'Effektiver Teilzeitwert');lock($('ptEffectiveSummary'),'Effektiver Teilzeitwert');
  }
  function card(){const more=$('tab-mehr');if(!more||$('proAccessCard'))return;const c=document.createElement('div');c.id='proAccessCard';c.className='card pro-access-card';c.innerHTML=`<div class="pro-access-head"><div><div class="pro-access-kicker">Entwicklungsmodus</div><h3>🔐 PRO-Testzugang</h3><p>Free und PRO sind technisch getrennt – noch ohne Zahlung oder echten Kauf.</p></div><button id="proAccessToggle" class="pro-access-toggle"></button></div><div id="proAccessState" class="pro-access-state"></div>`;const p=$('planPreview');p?p.before(c):more.prepend(c);$('proAccessToggle').onclick=()=>set(!active)}
  function plan(){const p=$('planPreview');if(!p)return;const k=p.querySelector('.plan-kicker'),b=p.querySelector('.plan-head .pro-badge'),n=p.querySelector('.plan-note'),t=p.querySelectorAll('.plan-tier');if(k)k.textContent='Produktstruktur';if(b)b.textContent=active?'PRO AKTIV':'FREE-MODUS';if(n)n.textContent='In der Entwicklungsphase kann PRO über den Testzugang ein- und ausgeschaltet werden.';if(t[0]&&!t[0].dataset.final){t[0].dataset.final='1';t[0].innerHTML='<strong>Free</strong><span>✓ Netto-Stundenwert</span><span>✓ Wunschgehalt</span><span>✓ Einfacher Jobvergleich</span><span>✓ Teilzeitvergleich</span><span>✓ Meine Daten</span><span>✓ Zentrale Ergebnisansicht</span>'}if(t[1]&&!t[1].dataset.final){t[1].dataset.final='1';t[1].innerHTML='<strong>PRO</strong><span>✓ Effektiver Jobwert</span><span>✓ Pendeln, Homeoffice & reale Kosten</span><span>✓ Benefits & Sonderzahlungen</span><span>✓ WasBinIchWert-Bewertung</span><span>✓ Mehrere Vergleiche speichern</span><span>✓ PDF & Teilen</span><span>✓ Gehaltsentwicklung</span><span>✓ Gehaltsverhandlung</span>'}}
  function apply(){mark();card();plan();const b=$('proAccessToggle'),s=$('proAccessState');if(b){b.textContent=active?'PRO aktiv':'Free testen';b.classList.toggle('on',active);b.setAttribute('aria-pressed',active?'true':'false')}if(s)s.innerHTML=active?'<b>PRO-Testzugang ist aktiv.</b> Alle Funktionen sind freigeschaltet.':'<b>Free-Modus ist aktiv.</b> PRO-Bereiche sind gesperrt.';document.querySelectorAll('[data-pro-action]').forEach(e=>{e.classList.toggle('pro-disabled',!active);e.setAttribute('aria-disabled',active?'false':'true');if(e.matches('details')){e.classList.toggle('pro-locked',!active);if(!active)e.open=false}});document.querySelectorAll('.pro-lockable').forEach(e=>e.classList.toggle('pro-off',!active));if(!active)['tab-gehalt','tab-verhandlung'].forEach(id=>{const e=$(id);if(e&&!e.classList.contains('hidden')){e.classList.add('hidden');$('tab-mehr')?.classList.remove('hidden')}})}
  function set(v){active=!!v;try{localStorage.setItem(KEY,active?'1':'0')}catch{}apply()}
  window.WIWPro={isActive:()=>active,setActive:set,require:f=>active?true:(popup(f),false)};
  document.addEventListener('click',e=>{const t=e.target.closest?.('[data-pro-action]');if(!t||active)return;e.preventDefault();e.stopImmediatePropagation();if(t.matches('details'))t.open=false;popup(t.dataset.proAction||'PRO-Funktion')},true);
  apply();
})();