const CACHE='wasbinichwert-pages-v843';
const LOCAL=['./','./index.html','./styles.css','./app.js','./comparison-table.js','./pdf-lib-loader.js','./pdf-export.js','./brand-runtime.js','./parttime.js','./salary-growth-fix.js','./salary-negotiation.js','./result-export.js','./onboarding.js','./pro-access.js','./offline-runtime.js','./brand-mark.svg','./manifest.webmanifest','./icon.svg'];
const PAP='https://cdn.jsdelivr.net/npm/lohnsteuerrechner/+esm';
const PDFLIB='https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js';
const CDN_HOST='cdn.jsdelivr.net';
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(CACHE);await c.addAll(LOCAL);for(const u of [PAP,PDFLIB]){try{const r=await fetch(u,{mode:'cors'});if(r.ok)await c.put(u,r.clone())}catch{}}self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(k!==CACHE)await caches.delete(k);await self.clients.claim()})()));
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET')return;
  const url=new URL(e.request.url);
  if(url.hostname===CDN_HOST){e.respondWith((async()=>{const c=await caches.open(CACHE),hit=await c.match(e.request)||await c.match(e.request.url);if(hit)return hit;try{const r=await fetch(e.request);if(r&&r.ok)await c.put(e.request,r.clone());return r}catch{if(e.request.url===PAP)return await c.match(PAP);if(e.request.url===PDFLIB)return await c.match(PDFLIB);throw new Error('offline')}})());return}
  if(url.origin!==self.location.origin)return;
  if(url.pathname.endsWith('/app.js')){e.respondWith((async()=>{const c=await caches.open(CACHE);let base,table,pdfLoader,pdf,brand,parttime,salaryFix,negotiation,resultExport,onboarding,proAccess,offlineRuntime;
    try{base=await fetch('./app.js',{cache:'no-store'});if(base.ok)await c.put('./app.js',base.clone());else throw new Error()}catch{base=await caches.match('./app.js')}
    try{table=await fetch('./comparison-table.js',{cache:'no-store'});if(table.ok)await c.put('./comparison-table.js',table.clone());else throw new Error()}catch{table=await caches.match('./comparison-table.js')}
    try{pdfLoader=await fetch('./pdf-lib-loader.js',{cache:'no-store'});if(pdfLoader.ok)await c.put('./pdf-lib-loader.js',pdfLoader.clone());else throw new Error()}catch{pdfLoader=await caches.match('./pdf-lib-loader.js')}
    try{pdf=await fetch('./pdf-export.js',{cache:'no-store'});if(pdf.ok)await c.put('./pdf-export.js',pdf.clone());else throw new Error()}catch{pdf=await caches.match('./pdf-export.js')}
    try{brand=await fetch('./brand-runtime.js',{cache:'no-store'});if(brand.ok)await c.put('./brand-runtime.js',brand.clone());else throw new Error()}catch{brand=await caches.match('./brand-runtime.js')}
    try{parttime=await fetch('./parttime.js',{cache:'no-store'});if(parttime.ok)await c.put('./parttime.js',parttime.clone());else throw new Error()}catch{parttime=await caches.match('./parttime.js')}
    try{salaryFix=await fetch('./salary-growth-fix.js',{cache:'no-store'});if(salaryFix.ok)await c.put('./salary-growth-fix.js',salaryFix.clone());else throw new Error()}catch{salaryFix=await caches.match('./salary-growth-fix.js')}
    try{negotiation=await fetch('./salary-negotiation.js',{cache:'no-store'});if(negotiation.ok)await c.put('./salary-negotiation.js',negotiation.clone());else throw new Error()}catch{negotiation=await caches.match('./salary-negotiation.js')}
    try{resultExport=await fetch('./result-export.js',{cache:'no-store'});if(resultExport.ok)await c.put('./result-export.js',resultExport.clone());else throw new Error()}catch{resultExport=await caches.match('./result-export.js')}
    try{onboarding=await fetch('./onboarding.js',{cache:'no-store'});if(onboarding.ok)await c.put('./onboarding.js',onboarding.clone());else throw new Error()}catch{onboarding=await caches.match('./onboarding.js')}
    try{proAccess=await fetch('./pro-access.js',{cache:'no-store'});if(proAccess.ok)await c.put('./pro-access.js',proAccess.clone());else throw new Error()}catch{proAccess=await caches.match('./pro-access.js')}
    try{offlineRuntime=await fetch('./offline-runtime.js',{cache:'no-store'});if(offlineRuntime.ok)await c.put('./offline-runtime.js',offlineRuntime.clone());else throw new Error()}catch{offlineRuntime=await caches.match('./offline-runtime.js')}
    const text=(await base.text())+'\n'+(await table.text())+'\n'+(await pdfLoader.text())+'\n'+(await pdf.text())+'\n'+(await brand.text())+'\n'+(await parttime.text())+'\n'+(await salaryFix.text())+'\n'+(await negotiation.text())+'\n'+(await resultExport.text())+'\n'+(await onboarding.text())+'\n'+(await proAccess.text())+'\n'+(await offlineRuntime.text());
    return new Response(text,{headers:{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'}})})());return}
  if(url.pathname.endsWith('/styles.css')||url.pathname.endsWith('/index.html')||url.pathname.endsWith('/icon.svg')||url.pathname.endsWith('/brand-mark.svg')||url.pathname.endsWith('/manifest.webmanifest')||url.pathname.endsWith('/pdf-lib-loader.js')||url.pathname.endsWith('/pdf-export.js')||url.pathname.endsWith('/parttime.js')||url.pathname.endsWith('/salary-growth-fix.js')||url.pathname.endsWith('/salary-negotiation.js')||url.pathname.endsWith('/result-export.js')||url.pathname.endsWith('/onboarding.js')||url.pathname.endsWith('/pro-access.js')||url.pathname.endsWith('/offline-runtime.js')||url.pathname.endsWith('/')){e.respondWith((async()=>{const c=await caches.open(CACHE);try{const r=await fetch(e.request,{cache:'no-store'});if(r.ok)await c.put(e.request,r.clone());return r}catch{return await caches.match(e.request)||await caches.match('./index.html')}})());return}
  e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request).then(r=>{if(r.ok)caches.open(CACHE).then(x=>x.put(e.request,r.clone()));return r}).catch(()=>caches.match('./index.html'))))
});